#ifndef DALProxyIRQLA640USBDEF_H
#define DALProxyIRQLA640USBDEF_H

#ifdef __cplusplus
namespace DALProxyIrqLA640USB_namespace
{
#endif

#define DAL_PROXYIrqLA640_IRIMAGE_WIDTH 640
#define DAL_PROXYIrqLA640_IRIMAGE_HEIGHT 512
#define DAL_PROXYIrqLA640_IRIMAGE_PIXEL 2
#define DAL_PROXYIrqLA640_IRIMAGE_RESOLUTION 16
#define DAL_PROXYIrqLA640_IRIMAGE_PIXEL_MAX 0xFFFF

#define DAL_PROXYIrqLA640_IRIMAGE_NBPIXELS (DAL_PROXYIrqLA640_IRIMAGE_WIDTH * DAL_PROXYIrqLA640_IRIMAGE_HEIGHT)

#define DAL_PROXYIrqLA640_IRIMAGE_PAYLOAD (DAL_PROXYIrqLA640_IRIMAGE_NBPIXELS * DAL_PROXYIrqLA640_IRIMAGE_PIXEL )

#define DAL_PROXYIrqLA640_IRIMAGE_TRAILERID 0
#define DAL_PROXYIrqLA640_IRIMAGE_FRAMEINFO 1
#define DAL_PROXYIrqLA640_IRIMAGE_META_TEMP 2
#define DAL_PROXYIrqLA640_IRIMAGE_ROI_X 4
#define DAL_PROXYIrqLA640_IRIMAGE_ROI_Y 5
#define DAL_PROXYIrqLA640_IRIMAGE_ROI_W 6
#define DAL_PROXYIrqLA640_IRIMAGE_ROI_H 7
#define DAL_PROXYIrqLA640_IRIMAGE_META_COUNTER 8
#define DAL_PROXYIrqLA640_IRIMAGE_META_MISSEDTRIGGERCOUNTER 9
#define DAL_PROXYIrqLA640_IRIMAGE_META_IMROCOUNTER 10
#define DAL_PROXYIrqLA640_IRIMAGE_TIMESTAMP 11
#define DAL_PROXYIrqLA640_IRIMAGE_FRAMEHISTO 13 // Warning : uint32*128 -> 128slots
#define DAL_PROXYIrqLA640_IRIMAGE_ENDFRAMEHISTO 267
#define DAL_PROXYIrqLA640_IRIMAGE_META_END (DAL_PROXYIrqLA640_IRIMAGE_ENDFRAMEHISTO+2)

/* Module Slot Type (see ProxyIRQLA640USB_SlotType() ) */
#define DAL_PROXYIrqLA640_SLOT_EMPTY 0
#define DAL_PROXYIrqLA640_SLOT_TYPE_GAIN 1
#define DAL_PROXYIrqLA640_SLOT_TYPE_OFFSET 2

/* NUC Slot Count */
#define DAL_PROXYIrqLA640_NUC_SLOT_COUNT 8
/* NUC Bank Count */
#define DAL_PROXYIrqLA640_NUC_BANK_COUNT 8

/* NUC Info free data size */
#define DAL_PROXYIrqLA640_NUC_INFO_USER_SIZE 60

/* Bank Settings count */
#define DAL_PROXYIrqLA640_BANK_SETTINGS_COUNT 8

// Maximum BAD Pixel allowed
#define DAL_PROXYIrqLA640_BADPIXELS_COUNT 2048

// Mask pixel type
#define DAL_PROXYIrqLA640_PIXEL_IGNORED 0
#define DAL_PROXYIrqLA640_PIXEL_ORIGINAL 1
#define DAL_PROXYIrqLA640_PIXEL_FIXED 2

// Feature string regular size
#define DAL_PROXYIrqLA640_FEATURE_STRING_SIZE 32

// Darkness settings
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_COUNT_V1             66
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_INFO_COUNT_V1        5 // 1 for version number, and 32 bytes (32/4 = 4) for the device serial number
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_COUNT_V2             52
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_PER_GAIN_COUNT_V2    23
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_INFO_COUNT_V2        5 // 1 for version number, and 32 bytes (32/8 = 4) for the device serial number
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_SIZE                 4096
#define DAL_PROXYIrqLA640_DARKNESS_TABLE_INFO_SIZE            256


#ifdef __cplusplus
}
#endif

#endif // DALProxyIRQLA640USBDEF_H
